stages:
  - test
  - build
  - run

lint:
  stage: test
  image: golangci/golangci-lint:v1.46.1
  script:
    - golangci-lint run -v -E golint -E gofmt -E goconst -E interfacer -E gocritic -E gocognit -E gocyclo
  except:
    - schedules

binary:
  stage: build
  image: golang:1.18-bullseye
  script: go build
  except:
    - schedules

check-availability:
  stage: run
  image: golang:1.18-bullseye
  variables:
    WHOIS_API_KEY: $WHOIS_API_KEY
  before_script:
    - go build
  script:
    - ./domain_name_checker $DOMAINS
  only:
    - schedules
